# -*- coding: utf-8 -*-
"""Trabajo Grupal 1_ Grupo 8_Sector de Real Estate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OzaWnJGJktf0b4xbTtgm5muts_yUW0xP

**Trabajo Práctico Grupal – Ciencia de Datos para Economistas**

Integrantes:


*   Jose Fabrizio Acosta Aguilera
*   Mateo Alejandro Bellota Delgado
*   Jose Adrian Castillo Saravia
*   Angela Micaela Salazar Silva
*   Michelle Vania Tovar Romero
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
import plotly.express as px
import plotly.graph_objects as go

"""#1) Obtener datos de precios desde la librería yfinance y validar que la importación se localice en un DataFrame de la librería pandas.

Primero, se define el periodo de análisis de los datos finales con las variables:
start_date: Fija la fecha de inicio en '2016-01-01'.
end_date: Fija la fecha de fin en '2026-01-01'.
Estas fechas se utilizarán para descargar los datos históricos de las empresas desde yfinance en el rango especificado.


Luego, usando la librería “yfinance”, se descargan los datos históricos de la acción de las empresas, cada una identificada por su ticker:
*   Empresa Prolongis,Inc. (PLD)
*   Ventas,Inc. (VTR)
*   Welltower Inc. (WELL)
*   Simon Property Group  (SPG)
*   Digital Realty Trust, Inc. (DLR)
*   Iron Mountain Inc. (IRM)
*   American Tower Corp. (AMT)
*   Equinix, Inc. (EQIX)
*   Realty Income Corp. (O)
*   Public Storage (PSA)




Finalmente, usa el código: yf.download('...', start=start_date, end=end_date, auto_adjust=False).
El parámetro auto_adjust=False significa que los precios históricos  no han sido modificados para reflejar ciertos eventos corporativos, como dividendos y divisiones de acciones (splits).
"""

#Fijamos fechas
start_date='2016-01-01'
end_date='2026-01-01'

from enum import auto
#Prolongis,Inc.
PLD=yf.download('PLD',start=start_date,end=end_date,auto_adjust=False)
PLD

print(type(PLD))

#Ventas, Inc.
VTR=yf.download('VTR',start=start_date,end=end_date,auto_adjust=False)
VTR

print(type(VTR))

#Welltower Inc.
WELL=yf.download('WELL',start=start_date,end=end_date,auto_adjust=False)
WELL

print(type(WELL))

#Simon Property Group
SPG=yf.download('SPG',start=start_date,end=end_date,auto_adjust=False)
SPG

print(type(SPG))

#Digital Realty Trust, Inc.
DLR=yf.download('DLR',start=start_date,end=end_date,auto_adjust=False)
DLR

print(type(DLR))

#Iron Mountain Inc.
IRM=yf.download('IRM',start=start_date,end=end_date,auto_adjust=False)
IRM

print(type(IRM))

#AMERICAN TOWER CORP.
AMT=yf.download('AMT',start=start_date,end=end_date,auto_adjust=False)
AMT

print(type(AMT))

#Equinix, Inc.
EQIX=yf.download('EQIX',start=start_date,end=end_date,auto_adjust=False)
EQIX

print(type(EQIX))

#Realty Income Corp.
O=yf.download('O',start=start_date,end=end_date,auto_adjust=False)
O

print(type(O))

#Public Storage
PSA=yf.download('PSA',start=start_date,end=end_date,auto_adjust=False)
PSA

print(type(PSA))

"""#2)Mostrar las primeras y últimas 5 filas del conjunto de datos.

Se usan los siguientes códigos:
*   .head() = Primeras 5 filas del DataFrame da una estructura al principio de tus datos y cuáles son los primeros valores.
"""

#Empresa Prolongis,Inc.
print(PLD.head())
print(PLD.tail())

#Digital Realty Trust, Inc.
print(DLR.head())
print(DLR.tail())

#AMERICAN TOWER CORP.
print(AMT.head())
print(AMT.tail())

#EQUINIX INC.
print(EQIX.head())
print(EQIX.tail())

#Ventas, Inc.
print(VTR.head())
print(VTR.tail())

#Iron Mountain Inc.
print(IRM.head())
print(IRM.tail())

#Simon Property Group
print(SPG.head())
print(SPG.tail())

#Prolongis, Inc
print(WELL.head())
print(WELL.tail())

#Realty Income Corp. (O)
print(O.head())
print(O.tail())

#Public Storage (PSA)
print(PSA.head())
print(PSA.tail())

"""#3) Identificar los tipos de datos y valores faltantes. Comentar que limpieza sería necesaria.

Se utiliza el código .info() para obtener el resumen de los datos financieros de cada empresa.

Los tipos de datos se identifican en la columna "Dtype":
*   float64= números con decimales
*   int64= números enteros

Para identificar si hay valores faltantes, se observa la columna "Non-Null Count". Si esta muestra que el número de variables no nulos es el mismo que el número total de entradas, entonces no hay valores faltantes.
"""

PLD.info()

AMT.info()

DLR.info()

EQIX.info()

IRM.info()

SPG.info()

VTR.info()

WELL.info()

O.info()

PSA.info()

"""#4) Identificar las principales medidas descriptivas. Calcule los principales estadísticos de la rentabilidad anual: Mediam Varianza, Mínimo, Máximo.

Primero, anualizamos los datos de cada empresa con el código:
*   _anual=df.resample('YE').last().pct_change()

Luego, definimos la rentabilidad anual de cada empresa con el código:
*   _anual['ret_anual']=_anual['Adj Close']


pct_change()
Finalmente, calcualmos los principales estadísticos con los respectivos códigos:
*   .std():.1% = Desviacion estandar anual
*   .var():.1% = Varianza anual
*   .mean():.1% = Retorno promedio
*   .min():.1% = Máxima caida anual
*   .max():.1% = Máxima subida anual
"""

PLD_anual=PLD.resample('YE').last()

PLD_anual['ret_anual']=PLD_anual['Adj Close'].pct_change()

print("Estadisticos de Prolongis,Inc.")
print(f'La desviacion estandar anual es de: {PLD_anual['ret_anual'].std():.1%}')
print(f'La varianza anual es de: {PLD_anual['ret_anual'].var():.1%}')
print(f'El retorno promedio es de: {PLD_anual['ret_anual'].mean():.1%}')
print(f'La maxima caida anual fue: {PLD_anual['ret_anual'].min():.1%}')
print(f'La maxima subida anual fue: {PLD_anual['ret_anual'].max():.1%}')

VTR_anual=VTR.resample('YE').last()

VTR_anual['ret_anual']=VTR_anual['Adj Close'].pct_change()

print("Estadisticos de Ventas, Inc.")
print(f'La desviacion estandar anual es de: {VTR_anual['ret_anual'].std():.1%}')
print(f'La varianza anual es de: {VTR_anual['ret_anual'].var():.1%}')
print(f'El retorno promedio es de: {VTR_anual['ret_anual'].mean():.1%}')
print(f'La maxima caida anual fue: {VTR_anual['ret_anual'].min():.1%}')
print(f'La maxima subida anual fue: {VTR_anual['ret_anual'].max():.1%}')

WELL_anual=WELL.resample('YE').last()

WELL_anual['ret_anual']=WELL_anual['Adj Close'].pct_change()

print("Estadisticos de Welltower Inc.")
print(f'La desviacion estandar anual es de: {WELL_anual['ret_anual'].std():.1%}')
print(f'La varianza anual es de: {WELL_anual['ret_anual'].var():.1%}')
print(f'El retorno promedio es de: {WELL_anual['ret_anual'].mean():.1%}')
print(f'La maxima caida anual fue: {WELL_anual['ret_anual'].min():.1%}')
print(f'La maxima subida anual fue: {WELL_anual['ret_anual'].max():.1%}')

SPG_anual=SPG.resample('YE').last()

SPG_anual['ret_anual']=SPG_anual['Adj Close'].pct_change()

print("Estadisticos de Simon Property Group")
print(f'La desviacion estandar anual es de: {SPG_anual['ret_anual'].std():.1%}')
print(f'La varianza anual es de: {SPG_anual['ret_anual'].var():.1%}')
print(f'El retorno promedio es de: {SPG_anual['ret_anual'].mean():.1%}')
print(f'La maxima caida anual fue: {SPG_anual['ret_anual'].min():.1%}')
print(f'La maxima subida anual fue: {SPG_anual['ret_anual'].max():.1%}')

DLR_anual=DLR.resample('YE').last()

DLR_anual['ret_anual']=DLR_anual['Adj Close'].pct_change()

print("Estadisticos de Digital Realty Trust, Inc.")
print(f'La desviacion estandar anual es de: {DLR_anual['ret_anual'].std():.1%}')
print(f'La varianza anual es de: {DLR_anual['ret_anual'].var():.1%}')
print(f'El retorno promedio es de: {DLR_anual['ret_anual'].mean():.1%}')
print(f'La maxima caida anual fue: {DLR_anual['ret_anual'].min():.1%}')
print(f'La maxima subida anual fue: {DLR_anual['ret_anual'].max():.1%}')

IRM_anual=IRM.resample('YE').last()

IRM_anual['ret_anual']=IRM_anual['Adj Close'].pct_change()

print("Estadisticos de Iron Mountain Inc.")
print(f'La desviacion estandar anual es de: {IRM_anual['ret_anual'].std():.1%}')
print(f'La varianza anual es de: {IRM_anual['ret_anual'].var():.1%}')
print(f'El retorno promedio es de: {IRM_anual['ret_anual'].mean():.1%}')
print(f'La maxima caida anual fue: {IRM_anual['ret_anual'].min():.1%}')
print(f'La maxima subida anual fue: {IRM_anual['ret_anual'].max():.1%}')

AMT_anual=AMT.resample('YE').last()

AMT_anual['ret_anual']=AMT_anual['Adj Close'].pct_change()

print("Estadisticos de AMERICAN TOWER CORP.")
print(f'La desviacion estandar anual es de: {AMT_anual['ret_anual'].std():.1%}')
print(f'La varianza anual es de: {AMT_anual['ret_anual'].var():.1%}')
print(f'El retorno promedio es de: {AMT_anual['ret_anual'].mean():.1%}')
print(f'La maxima caida anual fue: {AMT_anual['ret_anual'].min():.1%}')
print(f'La maxima subida anual fue: {AMT_anual['ret_anual'].max():.1%}')

EQIX_anual=EQIX.resample('YE').last()

EQIX_anual['ret_anual']=EQIX_anual['Adj Close'].pct_change()

print("Estadisticos de Equinix, Inc.")
print(f'La desviacion estandar anual es de: {EQIX_anual['ret_anual'].std():.1%}')
print(f'La varianza anual es de: {EQIX_anual['ret_anual'].var():.1%}')
print(f'El retorno promedio es de: {EQIX_anual['ret_anual'].mean():.1%}')
print(f'La maxima caida anual fue: {EQIX_anual['ret_anual'].min():.1%}')
print(f'La maxima subida anual fue: {EQIX_anual['ret_anual'].max():.1%}')

O_anual=O.resample('YE').last()

O_anual['ret_anual']=O_anual['Adj Close'].pct_change()

print("Estadisticos de Realty Income Corp.")
print(f'La desviacion estandar anual es de: {O_anual['ret_anual'].std():.1%}')
print(f'La varianza anual es de: {O_anual['ret_anual'].var():.1%}')
print(f'El retorno promedio es de: {O_anual['ret_anual'].mean():.1%}')
print(f'La maxima caida anual fue: {O_anual['ret_anual'].min():.1%}')
print(f'La maxima subida anual fue: {O_anual['ret_anual'].max():.1%}')

PSA_anual=PSA.resample('YE').last()

PSA_anual['ret_anual']=PSA_anual['Adj Close'].pct_change()

print("Estadisticos de Public Storage")
print(f'La desviacion estandar anual es de: {PSA_anual['ret_anual'].std():.1%}')
print(f'La varianza anual es de: {PSA_anual['ret_anual'].var():.1%}')
print(f'El retorno promedio es de: {PSA_anual['ret_anual'].mean():.1%}')
print(f'La maxima caida anual fue: {PSA_anual['ret_anual'].min():.1%}')

"""#5) Crear una nueva columna que calcule los retornos diarios.

Para calcular los retornos diarios, se usa el código pct_change() en la columna 'Close' (precio de cierre). Dando cambio porcentual entre el elemento actual y el anterior en la serie, es decir, el retorno diario del precio de cierre de las acciones de la empresa.
"""

VTR["Retorno_Diario_VTR"] = VTR['Close'].pct_change()
VTR

PLD["Retorno_Diario_PLD"]=PLD["Close"].pct_change()
PLD

WELL["Retorno_Diario_WELL"]=WELL["Close"].pct_change()
WELL

SPG["Retorno_Diario_SPG"]=SPG["Close"].pct_change()
SPG

DLR["Retorno_Diario_DLR"]=DLR["Close"].pct_change()
DLR

IRM["Retorno_Diario_IRM"]=IRM["Close"].pct_change()
IRM

AMT["Retorno_Diario_AMT"]=AMT["Close"].pct_change()
AMT

EQIX["Retorno_Diario_EQIX"]=EQIX["Close"].pct_change()
EQIX

O["Retorno_Diario_O"]=O["Close"].pct_change()
O

PSA["Retorno_Diario_PSA"]=PSA["Close"].pct_change()
PSA

"""#6) Crear una nueva columna que calcule los retornos diarios acumulados según el comando cumsum() y cumprod()

El comando cumprod() calcula el producto acumulado de los factores y refleja el crecimiento real del capital invertido. Es decir,los retornos diarios se multiplican de forma secuencial, reflejando la reinversión de ganancias. Se suma 1 a cada retorno diario para obtener un factor de crecimiento, se calcula el producto acumulado y luego se resta 1 para obtener el retorno acumulado como un porcentaje.

Por otro lado, el comando cumsum() es una aproximación lineal que calcula la suma acumulada de los retornos. Este no tiene en cuenta el efecto de la capitalización, lo que lleva a que subestime el rendimiento real en periodos largos o con alta volatibilidad.
"""

PLD["Retorno_Diario_Total_PLD"]=PLD["Adj Close"].pct_change()

PLD["Retorno_Diario_Total_Acumulado_Compuesto_PLD"] = (1 + PLD["Retorno_Diario_Total_PLD"]).cumprod() - 1
PLD["Retorno_Diario_Total_Acumulado_Lineal_PLD"] = PLD["Retorno_Diario_Total_PLD"].cumsum()

PLD

WELL["Retorno_Diario_Total_WELL"]=WELL["Adj Close"].pct_change()

WELL["Retorno_Diario_Total_Acumulado_Compuesto_WELL"] = (1 + WELL["Retorno_Diario_Total_WELL"]).cumprod() - 1
WELL["Retorno_Diario_Total_Acumulado_Lineal_WELL"] = WELL["Retorno_Diario_Total_WELL"].cumsum()
WELL

DLR["Retorno_Diario_Total_DLR"]=DLR["Adj Close"].pct_change()

DLR["Retorno_Diario_Total_Acumulado_Compuesto_DLR"] = (1 + DLR["Retorno_Diario_Total_DLR"]).cumprod() - 1
DLR["Retorno_Diario_Total_Acumulado_Lineal_DLR"] = DLR["Retorno_Diario_Total_DLR"].cumsum()
DLR

AMT["Retorno_Diario_Total_AMT"]=AMT["Adj Close"].pct_change()
AMT["Retorno_Diario_Total_Acumulado_Compuesto_AMT"] = (1 + AMT["Retorno_Diario_Total_AMT"]).cumprod() - 1
AMT["Retorno_Diario_Total_Acumulado_Lineal_AMT"] = AMT["Retorno_Diario_Total_AMT"].cumsum()
AMT

EQIX["Retorno_Diario_Total_EQIX"]=EQIX["Adj Close"].pct_change()

EQIX["Retorno_Diario_Total_Acumulado_Compuesto_EQIX"] = (1 + EQIX["Retorno_Diario_Total_EQIX"]).cumprod() - 1
EQIX["Retorno_Diario_Total_Acumulado_Lineal_EQIX"] = EQIX["Retorno_Diario_Total_EQIX"].cumsum()

EQIX

VTR["Retorno_Diario_Total_VTR"]=VTR["Adj Close"].pct_change()

VTR["Retorno_Diario_Total_Acumulado_Compuesto_VTR"] = (1 + VTR["Retorno_Diario_Total_VTR"]).cumprod() - 1
VTR["Retorno_Diario_Total_Acumulado_Lineal_VTR"] = VTR["Retorno_Diario_Total_VTR"].cumsum()
VTR

O["Retorno_Diario_Total_O"]=O["Adj Close"].pct_change()

O["Retorno_Diario_Total_Acumulado_Compuesto_O"] = (1 + O["Retorno_Diario_Total_O"]).cumprod() - 1
O["Retorno_Diario_Total_Acumulado_Lineal_O"] = O["Retorno_Diario_Total_O"].cumsum()
O

IRM["Retorno_Diario_Total_IRM"]=IRM["Adj Close"].pct_change()

IRM["Retorno_Diario_Total_Acumulado_Compuesto_IRM"] = (1 + IRM["Retorno_Diario_Total_IRM"]).cumprod() - 1
IRM["Retorno_Diario_Total_Acumulado_Lineal_IRM"] = IRM["Retorno_Diario_Total_IRM"].cumsum()
IRM

PSA["Retorno_Diario_Total_PSA"]=PSA["Adj Close"].pct_change()

PSA["Retorno_Diario_Total_Acumulado_Compuesto_PSA"] = (1 + PSA["Retorno_Diario_Total_PSA"]).cumprod() - 1
PSA["Retorno_Diario_Total_Acumulado_Lineal_PSA"] = PSA["Retorno_Diario_Total_PSA"].cumsum()
PSA

SPG["Retorno_Diario_Total_SPG"]=SPG["Adj Close"].pct_change()

SPG["Retorno_Diario_Total_Acumulado_Compuesto_SPG"] = (1 + SPG["Retorno_Diario_Total_SPG"]).cumprod() - 1
SPG["Retorno_Diario_Total_Acumulado_Lineal_SPG"] = SPG["Retorno_Diario_Total_SPG"].cumsum()
SPG

"""#7) Realizar gráficos que muestren:

##a)Retornos diarios en el periodo de análisis.

Se usa: ['Retorno_Diario_'].plot() , para generar un gráfico de líneas que muestra los retornos diarios de la empresaa lo largo del tiempo. Las líneas horizontales en negro (y=0) y rojo (y=0.1 y y=-0.1) sirven como referencias para identificar días con retornos nulos, subidas o caídas del 10%. También, se establecen las etiquetas para los ejes X e Y, y el título del gráfico.
"""

PLD['Retorno_Diario_PLD'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.axhline(y=0.1,color='r',linestyle='--')
plt.axhline(y=-0.1,color='r',linestyle='--')
plt.xlabel('Fecha')
plt.ylabel('Retorno diario total')
plt.title('Retorno diario total de PLD')
plt.show()

VTR['Retorno_Diario_VTR'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.axhline(y=0.1,color='r',linestyle='--')
plt.axhline(y=-0.1,color='r',linestyle='--')
plt.xlabel('Fecha')
plt.ylabel('Retorno diario total')
plt.title('Retorno diario total de VTR')
plt.show()

WELL['Retorno_Diario_WELL'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.axhline(y=0.1,color='r',linestyle='--')
plt.axhline(y=-0.1,color='r',linestyle='--')
plt.xlabel('Fecha')
plt.ylabel('Retorno diario total')
plt.title('Retorno diario total de WELL')
plt.show()

SPG['Retorno_Diario_SPG'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.axhline(y=0.1,color='r',linestyle='--')
plt.axhline(y=-0.1,color='r',linestyle='--')
plt.xlabel('Fecha')
plt.ylabel('Retorno diario total')
plt.title('Retorno diario total de SPG')
plt.show()

DLR['Retorno_Diario_DLR'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.axhline(y=0.1,color='r',linestyle='--')
plt.axhline(y=-0.1,color='r',linestyle='--')
plt.xlabel('Fecha')
plt.ylabel('Retorno diario total')
plt.title('Retorno diario total de DLR')
plt.show()

IRM['Retorno_Diario_IRM'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.axhline(y=0.1,color='r',linestyle='--')
plt.axhline(y=-0.1,color='r',linestyle='--')
plt.xlabel('Fecha')
plt.ylabel('Retorno diario total')
plt.title('Retorno diario total de IRM')
plt.show()

AMT['Retorno_Diario_AMT'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.axhline(y=0.1,color='r',linestyle='--')
plt.axhline(y=-0.1,color='r',linestyle='--')
plt.xlabel('Fecha')
plt.ylabel('Retorno diario total')
plt.title('Retorno diario total de AMT')
plt.show()

EQIX['Retorno_Diario_EQIX'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.axhline(y=0.1,color='r',linestyle='--')
plt.axhline(y=-0.1,color='r',linestyle='--')
plt.xlabel('Fecha')
plt.ylabel('Retorno diario total')
plt.title('Retorno diario total de EQIX')
plt.show()

O['Retorno_Diario_O'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.axhline(y=0.1,color='r',linestyle='--')
plt.axhline(y=-0.1,color='r',linestyle='--')
plt.xlabel('Fecha')
plt.ylabel('Retorno diario total')
plt.title('Retorno diario total de O')
plt.show()

PSA['Retorno_Diario_PSA'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.axhline(y=0.1,color='r',linestyle='--')
plt.axhline(y=-0.1,color='r',linestyle='--')
plt.xlabel('Fecha')
plt.ylabel('Retorno diario total')
plt.title('Retorno diario total de PSA')
plt.show()

"""##b)Retornos acumulados en el periodo de análisis: según cumsum y cumprod (gráfico lineal).

Se genera un gráfico de líneas para visualizar los retornos diarios acumulados compuestos. Primero, se trazan los datos de la columna 'Retorno_Diario_Total_Acumulado_Compuesto_' y se le agrega '.plot()' pra crear un gráfico de líneas.

También, se añade, para identificar si el retorno es negativo o positivo, una línea horizontal en el eje y=0 de color negro y discontinua.

Finalmente, se establecen el título del gráfico como 'Retorno diario acumulado de ', se etiqueta eje X como 'Fecha' y la del eje Y como 'Retorno total'.
"""

PLD['Retorno_Diario_Total_Acumulado_Compuesto_PLD'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.title('Retorno diario acumulado de PLD')
plt.xlabel('Fecha')
plt.ylabel('Retorno total')
plt.show()

VTR['Retorno_Diario_Total_Acumulado_Compuesto_VTR'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.title('Retorno diario acumulado de VTR')
plt.xlabel('Fecha')
plt.ylabel('Retorno total')
plt.show()

WELL['Retorno_Diario_Total_Acumulado_Compuesto_WELL'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.title('Retorno diario acumulado de WELL')
plt.xlabel('Fecha')
plt.ylabel('Retorno total')
plt.show()

SPG['Retorno_Diario_Total_Acumulado_Compuesto_SPG'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.title('Retorno diario acumulado de SPG')
plt.xlabel('Fecha')
plt.ylabel('Retorno total')
plt.show()

DLR['Retorno_Diario_Total_Acumulado_Compuesto_DLR'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.title('Retorno diario acumulado de DLR')
plt.xlabel('Fecha')
plt.ylabel('Retorno total')
plt.show()

IRM['Retorno_Diario_Total_Acumulado_Compuesto_IRM'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.title('Retorno diario acumulado de IRM')
plt.xlabel('Fecha')
plt.ylabel('Retorno total')
plt.show()

AMT['Retorno_Diario_Total_Acumulado_Compuesto_AMT'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.title('Retorno diario acumulado de AMT')
plt.xlabel('Fecha')
plt.ylabel('Retorno total')
plt.show()

EQIX['Retorno_Diario_Total_Acumulado_Compuesto_EQIX'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.title('Retorno diario acumulado de EQIX')
plt.xlabel('Fecha')
plt.ylabel('Retorno total')
plt.show()

O['Retorno_Diario_Total_Acumulado_Compuesto_O'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.title('Retorno diario acumulado de O')
plt.xlabel('Fecha')
plt.ylabel('Retorno total')
plt.show()

PSA['Retorno_Diario_Total_Acumulado_Compuesto_PSA'].plot()
plt.axhline(y=0,color='black',linestyle='--')
plt.title('Retorno diario acumulado de PSA')
plt.xlabel('Fecha')
plt.ylabel('Retorno total')
plt.show()

"""##c) Usar condicionales para clasificar el tipo de retorno acumulado en subida pronunciada, retorno moderado y estable o cayendo con la siguiente tabla sugerida:

*   Subida pronunciada: Retorno acumulado >= 40%
*   Retorno moderado: Retono acumulado entre >= 40%
*   Estable o cayendo: Retorno caída < 10%

Se calcula el retorno diario acumulado final de las empresas, para luego clasificarlas en lascategorías:'subida pronunciada', 'Retorno moderado' o 'Estable o cayendo', siguiendo los umbrales predefinidos.


Priemro se caocula el retorno final de las empresas, con el código:
 retorno_final_=['ret_diario_total_acum_'].iloc[-1]
 Se recupera la última entrada de la columna ['ret_diario_total_acum_'] con .iloc[-1], que representa el retorno diario acumulado final de la empresa durante todo el
 período de análisis.

Luego se clasifican los resultados codificando los las condiciones:
1.   if retorno_final_PLD >= 0.4 : Si el retorno acumulado final es mayor o igual a 40%, entonces se categoriza como si hubiera experimentado una'subida pronunciada'.
2.   elif retorno_final >= 0.10 : Si la primera condición es falsa, el código verifica esta segunda condición. Si retorno_final  es mayor o igual 10%, se clasifica como 'Retorno moderado'.
3.  else :  Si ninguna de las condiciones anteriores se cumple (retorno es inferior al 10%), la acción se clasifica como 'Estable o cayendo'

Finalmente, se usa el código: print(f'clasificacion:{categoria}'): , para  impirmir la clasificación determinada por las sentencias condicionales.
"""

retorno_final_PLD = PLD['Retorno_Diario_Total_Acumulado_Compuesto_PLD'].iloc[-1]
if retorno_final_PLD >=0.4:
  categoria = 'subida pronunciada'
elif retorno_final_PLD >= 0.10:
    categoria = "Retorno moderado"
else:
    categoria = "Estable o cayendo"

print(f'el retorno total de PLD fue de: {retorno_final_PLD:2%}')
print(f'clasificacion:{categoria}')

retorno_final_VTR = VTR['Retorno_Diario_Total_Acumulado_Compuesto_VTR'].iloc[-1]
if retorno_final_VTR >=0.4:
  categoria = 'subida pronunciada'
elif retorno_final_VTR >= 0.10:
    categoria = "Retorno moderado"
else:
    categoria = "Estable o cayendo"

print(f'el retorno total de VTR fue de: {retorno_final_VTR:2%}')
print(f'clasificacion:{categoria}')

retorno_final_WELL = WELL['Retorno_Diario_Total_Acumulado_Compuesto_WELL'].iloc[-1]
if retorno_final_WELL >=0.4:
  categoria = 'subida pronunciada'
elif retorno_final_WELL >= 0.10:
    categoria = "Retorno moderado"
else:
    categoria = "Estable o cayendo"

print(f'el retorno total de WELL fue de: {retorno_final_WELL:2%}')
print(f'clasificacion:{categoria}')

retorno_final_SPG = SPG['Retorno_Diario_Total_Acumulado_Compuesto_SPG'].iloc[-1]
if retorno_final_SPG >=0.4:
  categoria = 'subida pronunciada'
elif retorno_final_SPG >= 0.10:
    categoria = "Retorno moderado"
else:
    categoria = "Estable o cayendo"

print(f'el retorno total de SPG fue de: {retorno_final_SPG:2%}')
print(f'clasificacion:{categoria}')

retorno_final_DLR = DLR['Retorno_Diario_Total_Acumulado_Compuesto_DLR'].iloc[-1]
if retorno_final_DLR >=0.4:
  categoria = 'subida pronunciada'
elif retorno_final_DLR >= 0.10:
    categoria = "Retorno moderado"
else:
    categoria = "Estable o cayendo"

print(f'el retorno total de DLR fue de: {retorno_final_DLR:2%}')
print(f'clasificacion:{categoria}')

retorno_final_IRM = IRM['Retorno_Diario_Total_Acumulado_Compuesto_IRM'].iloc[-1]
if retorno_final_IRM >=0.4:
  categoria = 'subida pronunciada'
elif retorno_final_IRM >= 0.10:
    categoria = "Retorno moderado"
else:
    categoria = "Estable o cayendo"

print(f'el retorno total de IRM fue de: {retorno_final_IRM:2%}')
print(f'clasificacion:{categoria}')

retorno_final_AMT = AMT['Retorno_Diario_Total_Acumulado_Compuesto_AMT'].iloc[-1]
if retorno_final_AMT >=0.4:
  categoria = 'subida pronunciada'
elif retorno_final_AMT >= 0.10:
    categoria = "Retorno moderado"
else:
    categoria = "Estable o cayendo"

print(f'el retorno total de AMT fue de: {retorno_final_AMT:2%}')
print(f'clasificacion:{categoria}')

retorno_final_EQIX = EQIX['Retorno_Diario_Total_Acumulado_Compuesto_EQIX'].iloc[-1]
if retorno_final_EQIX >=0.4:
  categoria = 'subida pronunciada'
elif retorno_final_EQIX >= 0.10:
    categoria = "Retorno moderado"
else:
    categoria = "Estable o cayendo"

print(f'el retorno total de EQIX fue de: {retorno_final_EQIX:2%}')
print(f'clasificacion:{categoria}')

retorno_final_O = O['Retorno_Diario_Total_Acumulado_Compuesto_O'].iloc[-1]
if retorno_final_O >=0.4:
  categoria = 'subida pronunciada'
elif retorno_final_O >= 0.10:
    categoria = "Retorno moderado"
else:
    categoria = "Estable o cayendo"

print(f'el retorno total de O fue de: {retorno_final_O:2%}')
print(f'clasificacion:{categoria}')

retorno_final_PSA = PSA['Retorno_Diario_Total_Acumulado_Compuesto_PSA'].iloc[-1]
if retorno_final_PSA >=0.4:
  categoria = 'subida pronunciada'
elif retorno_final_PSA >= 0.10:
    categoria = "Retorno moderado"
else:
    categoria = "Estable o cayendo"

print(f'el retorno total de PSA fue de: {retorno_final_PSA:2%}')
print(f'clasificacion:{categoria}')

"""#8) Mostrar un ranking de retorno acumulado en el periodo de análisis entre los activos seleccionados.

Se acumulan cambios a lo largo del tiempo  y, al final, arma un ranking para ver cuáles tuvieron mejor rendimiento total.

Con la librería "pandas" se crea un diccionario llamado "all_daily_returns". Se usan los ticker y cada valor es una serie con sus retornos diarios acumulados. Estos son el cálculo del cambio porcentual entre el precio de cierre de un día y el anterior (pct_change()), y usando .squeeze() se asegura que sea una serie simple y no un DataFrame de una sola columna.

Posteriormente, el diccionaio se tranforma en el DataFrame "df_retornos" (se crea una tabla)

Luego, se calcula el retorno acumulado compuesto, se le suma 1 a cada retorno diario y se multiplicande forma acumulativa con "cumprod()", y finalmente se resta 1 para volver a expresarlo como retorno total.

Se toma la última fila, esta contiene el resultado final de cada empresa al cierre del período, con: "(df_acumulado.iloc[-1])".

Finalmente, se constuye un ranking ascendente  y se convierten en un nuevo DataFrame: "ranking_final". Este se  formatean como porcentajes con dos decimales con:"map(lambda x: '{:.2%}'.format(x))"
"""

all_daily_returns = {
    'PLD': PLD['Adj Close'].pct_change().squeeze(),
    'VTR': VTR['Adj Close'].pct_change().squeeze(),
    'WELL': WELL['Adj Close'].pct_change().squeeze(),
    'SPG': SPG['Adj Close'].pct_change().squeeze(),
    'DLR': DLR['Adj Close'].pct_change().squeeze(),
    'IRM': IRM['Adj Close'].pct_change().squeeze(),
    'AMT': AMT['Adj Close'].pct_change().squeeze(),
    'EQIX': EQIX['Adj Close'].pct_change().squeeze(),
    'O': O['Adj Close'].pct_change().squeeze(),
    'PSA': PSA['Adj Close'].pct_change().squeeze()
}

# Crear a DataFrame
df_retornos = pd.DataFrame(all_daily_returns)

# 1. Calculamos el retorno acumulado compuesto para todo el grupo
df_acumulado = (1 + df_retornos).cumprod() - 1

# 2. Extraemos la última fila (el rendimiento final)
ranking_serie = df_acumulado.iloc[-1]

# 3. Lo convertimos en DataFrame y ordenamos de mayor a menor
ranking_final = ranking_serie.sort_values(ascending=False).to_frame()
ranking_final.columns = ['Retorno Total']

# Formateamos la columna'Retorno Total' como porcentaje
ranking_final['Retorno Total'] = ranking_final['Retorno Total'].map(lambda x: '{:.2%}'.format(x))

display(ranking_final)

"""#9) Mostrar una tabla de doble entrada que muestre el tipo de retorno moderado y el numero de empresas.

Se define la función: 'clasificar_retorno', que tomará los retornos como entradas.

Luego se clasifican los resultados codificando los las condiciones:
1.   if retorno >= 0.4: Si el retornoes mayor o igual a 40%, entonces se categoriza como si hubiera experimentado una'subida pronunciada'.
2.   elif retorno >= 0.10: Si la primera condición es falsa, el código verifica esta segunda condición. Si retorno es mayor o igual 10%, se clasifica como 'Retorno moderado'.
3.  return :  Si ninguna de las condiciones anteriores se cumple (retorno es inferior al 10%), la acción se clasifica como 'Estable o cayendo'

 Luego, con '.apply()' se aplica esta función a la serie 'ranking_serie' , que contiene los retornos acumulados finales de cada empresa. Se contará cuantas empresas pertenecen a cada categoría con '.value_counts()'y se convertirán en un Dataframe de pandas con '.to_frame'. Este indica el 'Número de Empresas' para cada 'Tipo de Retorno'.
"""

def clasificar_retorno(retorno):
    if retorno >= 0.4:
        return 'Subida pronunciada'
    elif retorno >= 0.10:
        return 'Retorno moderado'
    else:
        return 'Estable o cayendo'

# Aplicar la función de clasificación a la serie de retornos finales
clasificaciones = ranking_serie.apply(clasificar_retorno)

# Contar el número de empresas en cada categoría
conteo_por_categoria = clasificaciones.value_counts().to_frame()
conteo_por_categoria.columns = ['Número de Empresas']
conteo_por_categoria.index.name = 'Tipo de Retorno'

display(conteo_por_categoria)

"""Se muestra cada empresa y su clasificación de retorno acumulado al final del periodo. Las filas representan las empresas, y la columna indica el tipo de retorno.

'Clasificaciones', contiene el tipo de retorno asignado a cada empresa y '.to_frame(name='Tipo de Retorno')'. convierte la serie en un Dataframe.
"""

# Convertir la serie de clasificaciones a un DataFrame para mostrarla como tabla
tabla_clasificacion_por_empresa = clasificaciones.to_frame(name='Tipo de Retorno')

display(tabla_clasificacion_por_empresa)

"""# 10) Análisis Creativo

## Gráfico de Retorno Total Acumulado por Empresa

Este gráfico de barras visualiza el retorno total acumulado de cada empresa a lo largo del periodo de análisis.
"""

# columna 'Retorno Total' de string a numérico
ranking_final_numeric = ranking_serie.sort_values(ascending=False).to_frame()
ranking_final_numeric.columns = ['Retorno Total']

plt.figure(figsize=(12, 6))
sns.barplot(x=ranking_final_numeric.index, y='Retorno Total', data=ranking_final_numeric, palette='viridis')
plt.title('Ranking de Retorno Total Acumulado de las Empresas')
plt.xlabel('Empresa')
plt.ylabel('Retorno Total Acumulado')
plt.xticks(rotation=45)
plt.axhline(y=0.4,color='r',linestyle='--')
plt.axhline(0, color='black', linestyle='--', linewidth=0.7)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""**PLD (Prologis)**

PLD es, sin duda, una de las empresas más fuertes del grupo. A lo largo del tiempo se comporta de manera bastante consistente: crece, se mantiene firme y cuando cae, logra recuperarse relativamente rápido. No es un crecimiento explosivo, pero sí muy sólido.
Las acciones parte de un precio aproximado desde niveles cercanos a 30–35 USD en 2016 y llega a valores alrededor de 120–130 USD en 2025, lo que implica que triplica su valor en el periodo.
Esto tiene correlación con lo que se dedica la empresa. Todo lo relacionado con logística y distribución ha ganado importancia en los últimos años, especialmente por el crecimiento del comercio electrónico. En ese contexto, PLD parece estar bien posicionada.
En cuanto al riesgo, no es una empresa extremadamente volátil. Sus activos, tienen sus subidas y bajadas regulares, pero en general se mantienen dentro de un rango razonable. Por eso, se puede ver como una opción bastante equilibrada al ofrecer buen crecimiento sin asumir riesgos excesivos.

**VTR (Ventas Inc.)**

VTR tiene un comportamiento más tranquilo. Crece con el tiempo, pero lo hace de manera más lenta y menos volátil que otras empresas del grupo. No destaca por grandes subidas, pero tampoco por caídas bruscas.
Ha pasado aproximadamente de 36 USD en 2016 a 77 USD en 2025, lo que significa que ha duplicado su valor en el periodo analizado, pero a un ritmo más lento que las otras empresas.
Además, se observa que en los últimos años el precio no pasa del rango de 75–80 USD, lo que indica que está en un periodo estable, o de estancamiento reciente.
Se nota que es una empresa más sensible a lo que pasa en la economía, especialmente en los últimos años donde su crecimiento parece haberse frenado un poco. Aun así, mantiene cierta estabilidad.

**WELL (Welltower)**

WELL se comporta de forma similar a VTR. Su crecimiento es progresivo pero constante. A lo largo del tiempo muestra resistencia ante caídas del mercado y recuperación progresiva, lo cual muestra su estabilidad como empresa.
Al inicio del periodo, parte en un rango de 60–65 USD y termina en uno de 90–100 USD, mostrando un crecimiento de alrededor de 50%–70% en todo el periodo.
Se concluye que WELL da la imagen que se estará haciendo una inversión con un agente confiable, aún si no es la más rentable, se apoya en su estabilidad, lo cual es apreciado por los inversionistas.

**SPG (Simon Property Group)**

SPG presenta un comportamiento más irregular que las anteriores empresas. Su comportamiento tiene altibajos más marcados, en más de un periodo, crece y cae de forma volátil.
Además tiene retornos desiguales, inicia cerca de 180–200 USD, tiene una fuerte caída por debajo de 80–100 USD en crisis y luego se tiene una recuperación parcial hacia niveles de 120–140 USD.
Se concluye que SPG es una empresa con retornos irregulares. Por cortos momentos del periodo puede dar buenos resultados, pero también implica asumir un mayor riesgo para un inversor. Se asume, que este comportamiento viene, en parte, porque es un activo “cíclico”, es decir, con una alta sensibilidad a las tasas de interés y al consumo discrecional (como el flujo de personas en centros comerciales).

**DLR (Digital Realty)**

DLR es una de las empresas con el mejor comportamiento en el análisis. Su crecimiento es claro, sube de forma constante y, si cae, tiene una eficaz recuperación..
Muestra un crecimiento aproximado a 70–80 USD hasta unos 140–160 USD, es decir, duplica su valor. No presenta movimientos exagerados, mostrando que tiene la capacidad de mantener un equilibrio entre riesgo y rendimiento. Además, se puede considerar que tiene una baja correlación con el ciclo económico tradicional, ya que depende más de la infraestructura digital (Data Centers), lo que la posiciona como una especie de “activo refugio moderno”.
En conjunto, DLR da la impresión de ser una empresa bien posicionada y con una tendencia favorable a largo plazo.

**IRM (Iron Mountain)**

IRM tiene un comportamiento interesante, pero presenta irregularidades. A lo largo del tiempo sí crece, pero no lo hace de manera tan lineal, como otras empresas. Presenta subidas y bajadas más marcadas.
IRM pasa de aproximadamente 25–30 USD a niveles cercanos a 80–90 USD, lo que implica que triplica su valor. No obstante, durante el periodo, presenta un altas fluctuaciones.
Esto implica que tiene un mayor riesgo, debido a que su comportamiento es poco predecible para los inversores. Sin embargo, el hecho de que su tendencia general siga siendo positiva indica que tiene potencial para los inversores.

**AMT (American Tower)**

AMT destaca dentro del grupo, pues presenta un crecimiento fuerte y sostenido, con una tendencia positiva a lo largo del periodo.
Esta empresa tiene un progreso fuerte, pasa de un promedio de 90–100 USD a 200–250 USD, teniendo más del doble de crecimiento.
A pesar de presentar cierta volatilidad, esta no opaca su rendimiento general. De hecho, ese nivel de variación es normal en empresas que presentan un crecimiento rápido.

**EQIX (Equinix)**

EQIX una de las empresas que más destaca entodo el análisis. Su crecimiento es superior al promedio y se mantiene consistente a lo largo del tiempo.
Pasa de aproximadamente 250–300 USD a más de 700–800 USD, es decir, su valor se ve triplicado al finalizar el periodo.
Lo interesante es que, a pesar de crecer bastante, no presenta una volatilidad excesiva. Esto la hace especialmente eficiente en términos de riesgo-retorno.
Al igual que DLR, EQIX presenta una baja correlación con el ciclo económico tradicional, ya que su negocio está altamente ligado a la infraestructura digital (Data Centers), lo que la convierte en un activo defensivo moderno dentro del sector.
En pocas palabras, EQIX combina lo mejor de ambos mundos: buen crecimiento y un nivel de riesgo controlado. Es una de las inversiones más sólidas dentro del conjunto.

**O (Realty Income)**

La empresa O tiene un comportamiento más conservador. Su crecimiento es moderado y bastante estable, sin grandes sobresaltos.
O pasa de un promedio de 45–50 a 60–70 USD, mostrando un crecimiento de alrededor de 30%–40% en todo el periodo.
No es una empresa que destaque por altos rendimientos, pero sí por su estabilidad frente a otras empresas del grupo.
En ese sentido, O funciona como una especie de “base” dentro del portafolio: no impulsa grandes ganancias, pero ayuda a mantener estabilidad.

**PSA (Public Storage)**

PSA se encuentra en un punto intermedio. Crece de forma sostenida, pero no al nivel de las empresas más destacadas. Tampoco presenta caídas fuertes, lo que la presenta como equilibrada.
PSA pasa de aproximadamente 200 a 300–320 USD, lo que implica un crecimiento de alrededor de 50%–60%.
Sin embargo, aunque creció, la empresa muestra que no llegó a su máximo histórico registrado, dado que, el 29 de diciembre del 2025 las acciones tuvieron el mayor valor llegando a uno 262.340 USD y el valor con el que termina las acciones en el 2025 es de 256.885 USD, mostrando un decrecimiento un aproximadamente 2%.
Otro datos resaltar, es que el volumen reduce considerablemente, empezando en el 2016 con 1´220´900 y terminando el 2025 con tan solo 815´200, lo que indica que existió menor interés, que se pudo encontrar con una menor actividad del mercado en comparación con años anteriores.
No sobresale especialmente en ningún aspecto, pero tampoco muestra debilidades claras. Es una empresa consistente, que cumple bien su función dentro del portafolio.
Se podría decir que PSA es una opción estable, con un balance razonable entre riesgo y crecimiento.

**ANÁLISIS COMPARATIVO ENTRE EMPRESAS**

Al comparar todas las empresas, se hace evidente que no todas se comportan igual, incluso estando dentro del mismo sector. Hay diferencias claras en cuánto crecen, qué tan estables son y qué nivel de riesgo implican.
Por un lado, están las empresas que lideran el crecimiento, como PLD (40 USD → 130 USD), EQIX (300 USD → 800 USD), AMT (100 USD → 250 USD) y IRM (30 USD → 90 USD). Estas destacan porque mantienen una tendencia positiva bastante clara y logran generar valor de forma constante en el tiempo. Son las que realmente impulsan el rendimiento del portafolio.
Por otro lado, hay empresas más tranquilas, como VTR (36 USD → 77 USD), WELL (60 USD→ 95 USD), PSA (200 USD → 320 USD) y DLR (80 USD → 150 USD). Estas no crecen tanto, pero ofrecen mayor estabilidad. Su función es más defensiva: ayudan a equilibrar el portafolio y reducir el riesgo general.
Finalmente, están casos como SPG (200 USD →  130 USD) e O (50 USD → 65 USD), que son más irregulares. Estas empresas tienen comportamientos menos predecibles, con subidas y bajadas más marcadas. Por eso, implican un mayor nivel de riesgo.
Algo que queda muy claro es que existe una relación directa entre riesgo y retorno. Las empresas que más crecen suelen tener más fluctuaciones, mientras que las más estables crecen menos. No hay una opción “perfecta”, todo depende del equilibrio que se quiera lograr.
Por último, también se nota que el tipo de negocio influye bastante. No basta con decir que todas son del mismo sector, ya que algunas están mejor posicionadas que otras dependiendo de hacia dónde va la economía.
"""

